---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Fetch and commit OUI content"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      -
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        # Settings -> Actions -> General -> Workflow Permissions
        # - select "Read repo contents", and
        # - enable "Allow Github Actions to create and approve pull requests"
        id: release
        with:
          release-type: simple
      -
        name: Clone Repo
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      -
        name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} oui.txt
